#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const outputDir = path.join(root, 'docs', 'generated');

function slugify(value) {
  const slug = value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return slug || 'generated-copy';
}

function buildMarkdown(payload) {
  const generatedAt = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

  return [
    `# ${payload.productName}`,
    '',
    `_Generated by n8n on ${generatedAt}_`,
    '',
    '## Short Ad Copy',
    payload.shortCopy,
    '',
    '## Social Post',
    payload.socialCopy,
    '',
    '## Landing Page Blurb',
    payload.landingCopy,
    '',
  ].join('\n');
}

function parsePayload(argv) {
  if (argv.length === 2 && argv[0] === '--base64') {
    return JSON.parse(Buffer.from(argv[1], 'base64').toString('utf8'));
  }

  if (argv.length === 1) {
    return JSON.parse(argv[0]);
  }

  throw new Error("Usage: render_content.mjs '<json-payload>' or render_content.mjs --base64 '<base64-json-payload>'");
}

try {
  const payload = parsePayload(process.argv.slice(2));
  const requiredFields = ['productName', 'shortCopy', 'socialCopy', 'landingCopy'];
  const missing = requiredFields.filter((field) => !payload[field]);

  if (missing.length > 0) {
    throw new Error(`Missing required fields: ${missing.join(', ')}`);
  }

  fs.mkdirSync(outputDir, { recursive: true });

  const slug = slugify(payload.productName);
  const outputFile = path.join(outputDir, `${slug}.md`);
  fs.writeFileSync(outputFile, buildMarkdown(payload), 'utf8');

  console.log(JSON.stringify({
    status: 'ok',
    outputFile,
    slug,
  }));
} catch (error) {
  console.error(String(error.message || error));
  process.exit(1);
}
