#!/usr/bin/env python3
import base64
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = ROOT / "docs" / "generated"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "generated-copy"


def build_markdown(payload: dict) -> str:
    product_name = payload["productName"].strip()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    sections = [
        f"# {product_name}",
        "",
        f"_Generated by n8n on {generated_at}_",
        "",
        "## Short Ad Copy",
        payload["shortCopy"].strip(),
        "",
        "## Social Post",
        payload["socialCopy"].strip(),
        "",
        "## Landing Page Blurb",
        payload["landingCopy"].strip(),
        "",
    ]
    return "\n".join(sections)


def main() -> int:
    if len(sys.argv) != 2 and len(sys.argv) != 3:
        print("Usage: render_content.py '<json-payload>'", file=sys.stderr)
        print("   or: render_content.py --base64 '<base64-json-payload>'", file=sys.stderr)
        return 1

    try:
        if len(sys.argv) == 3 and sys.argv[1] == "--base64":
            decoded = base64.b64decode(sys.argv[2]).decode("utf-8")
            payload = json.loads(decoded)
        else:
            payload = json.loads(sys.argv[1])
    except (json.JSONDecodeError, ValueError, base64.binascii.Error) as exc:
        print(f"Invalid payload: {exc}", file=sys.stderr)
        return 1

    required_fields = ["productName", "shortCopy", "socialCopy", "landingCopy"]
    missing = [field for field in required_fields if not payload.get(field)]
    if missing:
        print(f"Missing required fields: {', '.join(missing)}", file=sys.stderr)
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    slug = slugify(payload["productName"])
    output_file = OUTPUT_DIR / f"{slug}.md"
    output_file.write_text(build_markdown(payload), encoding="utf-8")

    result = {
        "status": "ok",
        "outputFile": str(output_file),
        "slug": slug,
    }
    print(json.dumps(result))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
